# Generated by Django 5.2.2 on 2025-06-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['title'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
    ]
