# Generated by Django 5.2.2 on 2025-06-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_location_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='number',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
